version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: antiplagdb
      POSTGRES_USER: postgres      # Стандартный пользователь
      POSTGRES_PASSWORD: postgres  # Простой пароль
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - antplag-network
    ports:
      - "5432:5432"  # Для проверки

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - antplag-network
    depends_on:
      - file-storing-service
      - file-analysis-service

  file-storing-service:
    build: ./file-storing-service
    networks:
      - antplag-network
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/antiplagdb
      - SPRING_DATASOURCE_USERNAME=postgres    # Изменено
      - SPRING_DATASOURCE_PASSWORD=postgres    # Изменено
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres

  file-analysis-service:
    build: ./file-analysis-service
    networks:
      - antplag-network
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/antiplagdb
      - SPRING_DATASOURCE_USERNAME=postgres    # Изменено
      - SPRING_DATASOURCE_PASSWORD=postgres    # Изменено
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
      - file-storing-service

networks:
  antplag-network:

volumes:
  postgres_data: